// This file has been generated by Specta. DO NOT EDIT.

export type ReflectorType = "Rectangular" | "Trapezoidal"

export type ReflectiveMaterial = "AF" | "TF" | "MS" | "RT" | "SR2000" | "SRV"

export type WindowMaterial = "SingleMylar" | "DoubleMylar"

export type Absorber = "BCS" | "TSC"

export type Oven = [Absorber, WindowMaterial, BodyMaterial, BodyMaterial, Insulator, ReflectorType, ReflectiveMaterial, number]

export type GraphDataResponse = "Tio" | "Cost" | "PerformanceIndex" | "Score"

export type Insulator = "N" | "FG" | "SF" | "DF" | "FG30"

export type Payload = { oven: Oven; reflector_ml: number; data_type: GraphDataResponse }

export type BodyMaterial = "C" | "W16"

